---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress
    app: haproxy-ingress
    tier: ingress
  name: haproxy-ingress
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      run: haproxy-ingress
      tier: ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
        tier: ingress
    spec:
      serviceAccountName: ingress-controller
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - haproxy-ingress
            topologyKey: kubernetes.io/hostname
      priorityClassName: infra
      containers:
        - name: haproxy-ingress
          image: quay.io/jcmoraisjr/haproxy-ingress:v0.7-beta.8
          args:
          - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
          - --default-ssl-certificate=$(POD_NAMESPACE)/star-letsencrypt-cert
          - --configmap=$(POD_NAMESPACE)/haproxy-ingress
          - --allow-cross-namespace=true
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /healthz
              port: 10253
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 10253
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          - name: stat
            containerPort: 1936
          - name: healthz
            containerPort: 10253
          resources:
            requests:
              cpu: "100m"
              memory: "150Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        - name: haproxy-exporter
          image: quay.io/prometheus/haproxy-exporter:v0.9.0
          args:
          - --haproxy.scrape-uri=http://localhost:1936/;csv
          ports:
          - name: metrics
            containerPort: 9101
          securityContext:
            runAsUser: 65534
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 9101
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 9101
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "150m"
              memory: "150Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: mintel/fluentd-es-image:v2.2.1-1
          name: haproxy-fluentd
          env:
          - name: FLUENTD_ARGS
            value: --no-supervisor
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          #- name: CLUSTER_NAME
          #  value: {{cluster_name}}
          #- name: CLUSTER_ENVIRONMENT
          #  value: {{cluster_environment}}
          resources:
            requests:
              cpu: "50m"
              memory: "150Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "150m"
              memory: "350Mi"
              ephemeral-storage: "2Gi"
          ports:
            - containerPort: 9001
            - containerPort: 8888
            - containerPort: 24231
          securityContext:
            runAsUser: 65534
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
          - name: config-volume
            mountPath: /etc/fluent/fluent.conf
            subPath: fluent.conf
      volumes:
      - name: config-volume
        configMap:
          name: haproxy-fluentd
