apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: star-letsencrypt-cert
spec:
  acme:
    config:
    - dns01:
        provider: $(DNS_LETSENCRYPT_PROVIDER)
      domains:
      - '*.$(DOMAIN)'
  commonName: '*.$(DOMAIN)'
  issuerRef:
    name: $(DNS_LETSENCRYPT_KEYNAME)
  secretName: star-letsencrypt-cert

