apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: star-letsencrypt-cert
spec:
  acme:
    config:
    - dns01:
        provider: __PLACEHOLDER_PATCH__
      domains:
      - '*.svc.$(DOMAIN)'
  commonName: '*.svc.$(DOMAIN)'
  issuerRef:
    name: __PLACEHOLDER_PATCH__
  secretName: star-letsencrypt-cert

