---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: monitoring

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

commonLabels:
  app.kubernetes.io/app: elasticsearch-curator
  app: elasticsearch-curator

resources:
- es-curator-job.yml

configMapGenerator:
- name: elasticsearch-log-curator-config
  files:
  - files/action_file.yml
  - files/config.yml

images:
- name: quay.io/pires/docker-elasticsearch-curator
  newTag: 5.5.1
