apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  baseImage: quay.io/prometheus/alertmanager
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - alertmanager
            - key: alertmanager
              operator: In
              values:
              - main
          topologyKey: kubernetes.io/hostname
        weight: 100
  replicas: 3
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  priorityClassName: infra
  resources:
    limits:
      cpu: 150m
      memory: 500Mi
    requests:
      cpu: 50m
      memory: 400Mi
  retention: 120h
  version: v0.16.1
