---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: default

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

commonLabels:
  app.kubernetes.io/app: reloader
  app: reloader

resources:
  - sa.yaml
  - deployment.yaml

images:
  - name: stakater/reloader
    newTag: v0.0.26
