---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vault-configurator
    vault_cr: $(VAULT_CR_LABEL)
  name: vault-jwt-auth
data:
  vault-config.yml: |-
    auth:
      - type: jwt
        path: jwt
        config:
          oidc_discovery_url: https://dex.svc.dev1.k8s-dev.mintel.com
          bound_issuer: https://dex.svc.dev1.k8s-dev.mintel.com
          default_role: default
        roles:
          - name: admin
            role_type: jwt
            bound_audiences:
              - dev1
            user_claim: email
            groups_claim: "groups"
            policies: ""
            ttl: 10m
            max_ttl: 60m
            num_uses: 3
          - name: mintel
            role_type: jwt
            bound_audiences:
              - dev1
            user_claim: email
            groups_claim: "groups"
            policies: ""
            ttl: 10m
            max_ttl: 60m
            num_uses: 3
          - name: mintel2
            role_type: jwt
            bound_audiences:
              - dev1
            user_claim: email
            groups_claim: "groups"
            policies: ""
            ttl: 10m
            max_ttl: 60m
            num_uses: 3
