# vim:ft=python.jinja2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-log-master
  labels:
    tier: logging-plane
spec:
  serviceName: elasticsearch-log-discovery
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tier: logging-plane
  template:
    metadata:
      labels:
        tier: logging-plane
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - elasticsearch-log
                - key: role
                  operator: In
                  values:
                  - master
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      terminationGracePeriodSeconds: 180
      priorityClassName: infra
      containers:
      - name: es-master
        image: mintel/elasticsearch:v6.6.0-1
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command: [ "/usr/bin/bash", "-c", "sleep 60" ]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: logs
        - name: POST_TERM_WAIT
          value: "15"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-log-discovery.monitoring.svc.cluster.local"
        - name: MINIMUM_NUMBER_OF_MASTERS
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "true"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: NETWORK_ADDRESS_CACHE_TTL
          value: "2"
        - name: NETWORK_ADDRESS_CACHE_NEGATIVE_TTL
          value: "2"
        - name: ES_JAVA_OPTS
          value: "-Xms2048m -Xmx2048m"
        # PROCESSORS NEED TO BE AN INTEGER - SET LIMITS CPU ACCORDINGLY
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 250m
            memory: 4Gi
          limits:
            cpu: "2"
            memory: 4Gi
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 40
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
