---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1


commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

commonLabels:
  app.kubernetes.io/app: cert-manager
  app: cert-manager

resources:
  - crd-certificates.yaml
  - crd-challenges.yaml
  - crd-clusterissuers.yaml
  - crd-issuers.yaml
  - crd-orders.yaml
