---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    mintel.com/skip-local-ci: true
  labels:
    app: vault-configurator
    vault_cr: $(VAULT_CR_LABEL)
  name: vault-gcp-secret-backend
data:
  vault-config.yml: |
    secrets:
      - type: gcp
        path: gcp/
        description: Google cloud secrets
        config:
          credentials: ""
          ttl: "30m"
          max_ttl: "60m"
        configuration:
            roleset:
              - name: terraform-provisioner
                secret_type: "service_account_key"
                project: "$(GOOGLE_PROJECT)"
                bindings: |
                  resource "//cloudresourcemanager.googleapis.com/projects/$(GOOGLE_PROJECT)" {
                    roles = ["roles/editor"]
                  }
              - name: terraform-provisioner-token
                secret_type: "access_token"
                token_scopes:
                  - "https://www.googleapis.com/auth/cloud-platform"
                project: "$(GOOGLE_PROJECT)"
                bindings: |
                  resource "//cloudresourcemanager.googleapis.com/projects/$(GOOGLE_PROJECT)" {
                    roles = ["roles/editor"]
                  }
