---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    mintel.com/skip-ci: true
  labels:
    app: vault-configurator
    vault_cr: $(VAULT_CR_LABEL)
  name: kubernetes-local-auth-config
data:
  vault-config.yml: |
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: default
            bound_service_account_namespaces: default
            ttl: 1h
