---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

configurations:
- varreference.yaml

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

resources:
- base-policies.yaml # All Common base policies
- base-auth.yaml # All Common auth configurations
- gcp-secret-backend.yaml # GCP Secret Backend

vars:
- name: VAULT_CR_LABEL
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vault-policies-properties
  fieldref:
    fieldpath: data.VAULT_CR_LABEL
- name: GOOGLE_PROJECT
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: vault-policies-properties
  fieldref:
    fieldpath: data.GOOGLE_PROJECT

configMapGenerator:
- name: vault-policies-properties 
  env: properties/policies.properties

