apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 1
  image: vault:$(VAULT_VERSION)
  bankVaultsImage: banzaicloud/bank-vaults:$(BANK_VAULTS_VERSION)

  podAntiAffinity: failure-domain.beta.kubernetes.io/zone
  serviceType: ClusterIP

  serviceAccount: $(SERVICEACCOUNT_NAME)

  servicePorts:
    api-port: 8200
    cluster-port: 8201
    external-port: 8300

  volumes:
    - name: letsencrypt-ssl
      secret:
        defaultMode: 420
        secretName: $(VAULTCRD_NAME)-letsencrypt-cert

  volumeMounts:
    - name: letsencrypt-ssl
      mountPath: /etc/cert-manager

  config:
    listener:
      - tcp:
          address: "0.0.0.0:8300"
          tls_cert_file: /etc/cert-manager/tls.crt
          tls_key_file: /etc/cert-manager/tls.key
          tls_min_version: "tls12"
          tls_disable: "false"
      - tcp:
          address: "0.0.0.0:8200"
          tls_cert_file: /vault/tls/server.crt
          tls_key_file: /vault/tls/server.key
          tls_min_version: "tls12"
          tls_disable: "false"
    #api_addr: https://$(VAULTCRD_NAME).$(VAULTCRD_NAMESPACE).svc.cluster.local:8200
    api_addr: https://$(VAULTCRD_NAME).svc.$(DOMAIN)
    cluster_name: "$(VAULTCRD_NAME)"
    telemetry:
      statsd_address: localhost:9125
    ui: true

  externalConfig:
    audit:
    - type: file
      description: "STDOUT Audit logging"
      options:
        file_path: stdout
