apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: 1
  image: vault:$(VAULT_VERSION)
  bankVaultsImage: banzaicloud/bank-vaults:$(BANK_VAULTS_VERSION)

  podAntiAffinity: failure-domain.beta.kubernetes.io/zone
  serviceType: ClusterIP

  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: $(SERVICEACCOUNT_NAME)

  # Use local disk to store Vault file data, see config section.
  volumes:
    - name: vault-file
      persistentVolumeClaim:
        claimName: vault-file

  volumeMounts:
    - name: vault-file
      mountPath: /vault/file

  # Describe where you would like to store the Vault unseal keys and root token.
  unsealConfig:
    kubernetes:
      secretNamespace: $(SERVICEACCOUNT_NAMESPACE)

  # A YAML representation of a final vault config file, this config represents
  # a HA config in Google Cloud.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      file:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
        tls_min_version: "tls12"
        tls_disable: "false"
    api_addr: https://vault.$(SERVICEACCOUNT_NAMESPACE).svc.cluster.local:8200
    cluster_name: "vault"
    telemetry:
      statsd_address: localhost:9125
    ui: true

  # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
  externalConfig:
    audit:
    - type: file
      description: "STDOUT Audit logging"
      options:
        file_path: stdout
