---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

commonLabels:
  app.kubernetes.io/app: sealed-secrets

namespace: kube-system

resources:
- crd.yaml
- clusterrolebinding.yaml
- clusterrole.yaml
- rolebinding.yaml
- role.yaml
- sa.yaml
- service.yaml
- deployment.yaml

images:
  - name: quay.io/bitnami/sealed-secrets-controller:v0.7.0
    newTag: v0.7.0
