---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reloader
spec:
  template:
    spec:
      containers:
        - name: reloader
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
