---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: reloader-role
rules:
  - apiGroups:
      - ""
    resources:      
      - secrets
      - configmaps
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "extensions"
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
