---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: monitoring

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

commonLabels:
  app.kubernetes.io/app: elasticsearch-log
  app: elasticsearch-log
  role: data

resources:
- es-data-pdb.yml
- es-data-stateful.yml
- es-data-svc.yml

images:
- name: mintel/elasticsearch
  newTag: v6.6.0-1
