kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize

resources:
- deploy.yaml
- service.yaml
  #- service-monitor.yaml
- ingress.yaml
