apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-log-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: logging-plane
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: logging-plane
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
      priorityClassName: infra
      containers:
        - name: exporter
          image: justwatch/elasticsearch_exporter:1.0.2
          imagePullPolicy: IfNotPresent
          command: ["elasticsearch_exporter",
                    "-es.uri=http://elasticsearch-log-discovery:9200",
                    "-es.all=true",
                    "-es.indices=true",
                    "-es.timeout=30s",
                    "-web.listen-address=:9108",
                    "-web.telemetry-path=/metrics"]
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 9108
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
