apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elasticsearch-log-exporter
spec:
  endpoints:
  - interval: 10s
    port: http
  jobLabel: app
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: elasticsearch-log-exporter